#!/usr/bin/env python3
"""
Fase M1 — Auditoria Municipal: Template Fix Global
Percorre todos os 148 JSONs municipais e:
1. Corrige rendaPerCapita 706 → 810.5 (meio SM 2026)
2. Adiciona "verified": false + "templateGenerated": true nos templates universais
3. Adiciona disclaimer "Verifique disponibilidade na prefeitura" nos templates
4. Atualiza lastUpdated para 2026-02-07
5. Valida: JSON parse, IDs únicos, contagem
"""

import json
import os
import sys
from pathlib import Path

MUNICIPALITIES_DIR = Path(__file__).parent.parent / "frontend" / "src" / "data" / "benefits" / "municipalities"

# Template benefit ID suffixes (universal, generated by script)
TEMPLATE_SUFFIXES = [
    "restaurante-popular",
    "transporte-social",
    "iptu-social",
    "habitacao-municipal",
    "capacitacao-emprego",
    "farmacia-municipal",
]

# SM 2026 corrections
SM_FIXES = {
    706: 810.5,     # meio SM 2025 → 2026
    706.0: 810.5,
    1412: 1621,     # SM 2025 → 2026
    1412.0: 1621,
    2640: 2850,     # MCMV Faixa 1
    2640.0: 2850,
    3036: 3242,     # 2 SM
    3036.0: 3242,
}

DISCLAIMER = " Verifique disponibilidade na prefeitura da sua cidade."


def is_template_benefit(benefit_id: str) -> bool:
    """Check if benefit ID matches a universal template pattern."""
    for suffix in TEMPLATE_SUFFIXES:
        if benefit_id.endswith(suffix):
            return True
    return False


def fix_renda_values(rules: list) -> int:
    """Fix outdated SM-based rendaPerCapita values. Returns count of fixes."""
    fixes = 0
    for rule in rules:
        if rule.get("field") == "rendaPerCapita" and rule.get("value") in SM_FIXES:
            old_val = rule["value"]
            new_val = SM_FIXES[old_val]
            rule["value"] = new_val
            # Update description if it mentions the old value
            desc = rule.get("description", "")
            if str(int(old_val)) in desc:
                rule["description"] = desc.replace(str(int(old_val)), str(new_val) if new_val == int(new_val) else f"{new_val:.2f}".replace(".", ","))
            elif "meio salário mínimo" in desc.lower():
                rule["description"] = "Renda por pessoa até meio salário mínimo"
            fixes += 1
    return fixes


def add_template_metadata(benefit: dict) -> bool:
    """Add verified=false and templateGenerated=true to template benefits."""
    if is_template_benefit(benefit["id"]):
        changed = False
        if "verified" not in benefit:
            benefit["verified"] = False
            changed = True
        if "templateGenerated" not in benefit:
            benefit["templateGenerated"] = True
            changed = True
        return changed
    return False


def add_disclaimer(benefit: dict) -> bool:
    """Add disclaimer to template benefit shortDescription if not already present."""
    if is_template_benefit(benefit["id"]):
        desc = benefit.get("shortDescription", "")
        if "Verifique" not in desc and DISCLAIMER.strip() not in desc:
            benefit["shortDescription"] = desc.rstrip(".") + "." + DISCLAIMER
            return True
    return False


def process_file(filepath: Path) -> dict:
    """Process a single municipal JSON file. Returns stats."""
    stats = {
        "file": filepath.name,
        "renda_fixes": 0,
        "metadata_added": 0,
        "disclaimers_added": 0,
        "benefits_count": 0,
    }

    with open(filepath, "r", encoding="utf-8") as f:
        data = json.load(f)

    data["lastUpdated"] = "2026-02-07"
    benefits = data.get("benefits", [])
    stats["benefits_count"] = len(benefits)

    for benefit in benefits:
        # Fix SM values in eligibility rules
        stats["renda_fixes"] += fix_renda_values(benefit.get("eligibilityRules", []))

        # Add template metadata
        if add_template_metadata(benefit):
            stats["metadata_added"] += 1

        # Add disclaimer to templates
        if add_disclaimer(benefit):
            stats["disclaimers_added"] += 1

        # Update benefit lastUpdated
        benefit["lastUpdated"] = "2026-02-07"

    with open(filepath, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
        f.write("\n")

    return stats


def validate_all() -> bool:
    """Validate all municipal JSONs after processing."""
    all_ids = set()
    errors = []
    total_benefits = 0
    file_count = 0

    for filepath in sorted(MUNICIPALITIES_DIR.glob("*.json")):
        file_count += 1
        try:
            with open(filepath, "r", encoding="utf-8") as f:
                data = json.load(f)
        except json.JSONDecodeError as e:
            errors.append(f"  JSON parse error in {filepath.name}: {e}")
            continue

        benefits = data.get("benefits", [])
        total_benefits += len(benefits)

        for b in benefits:
            bid = b.get("id", "MISSING_ID")
            if bid in all_ids:
                errors.append(f"  Duplicate ID: {bid} in {filepath.name}")
            all_ids.add(bid)

            # Check for old SM values
            for rule in b.get("eligibilityRules", []):
                if rule.get("field") == "rendaPerCapita" and rule.get("value") in (706, 706.0, 1412, 1412.0):
                    errors.append(f"  Old SM value {rule['value']} in {bid}")

    print(f"\n{'='*60}")
    print(f"VALIDAÇÃO")
    print(f"{'='*60}")
    print(f"  Arquivos: {file_count}")
    print(f"  Benefícios totais: {total_benefits}")
    print(f"  IDs únicos: {len(all_ids)}")

    if errors:
        print(f"\n  ERROS ({len(errors)}):")
        for e in errors:
            print(e)
        return False
    else:
        print(f"  ✓ Zero erros!")
        return True


def main():
    print("=" * 60)
    print("Fase M1 — Auditoria Municipal: Template Fix Global")
    print("=" * 60)

    json_files = sorted(MUNICIPALITIES_DIR.glob("*.json"))
    print(f"\nProcessando {len(json_files)} arquivos municipais...\n")

    total_stats = {
        "renda_fixes": 0,
        "metadata_added": 0,
        "disclaimers_added": 0,
        "total_benefits": 0,
    }

    for filepath in json_files:
        stats = process_file(filepath)
        total_stats["renda_fixes"] += stats["renda_fixes"]
        total_stats["metadata_added"] += stats["metadata_added"]
        total_stats["disclaimers_added"] += stats["disclaimers_added"]
        total_stats["total_benefits"] += stats["benefits_count"]

        if stats["renda_fixes"] > 0 or stats["metadata_added"] > 0:
            print(f"  {filepath.name}: renda={stats['renda_fixes']}, meta={stats['metadata_added']}, disc={stats['disclaimers_added']}")

    print(f"\n{'='*60}")
    print(f"RESUMO")
    print(f"{'='*60}")
    print(f"  Arquivos processados: {len(json_files)}")
    print(f"  Benefícios totais: {total_stats['total_benefits']}")
    print(f"  Correções rendaPerCapita: {total_stats['renda_fixes']}")
    print(f"  Metadata adicionada: {total_stats['metadata_added']}")
    print(f"  Disclaimers adicionados: {total_stats['disclaimers_added']}")

    ok = validate_all()
    sys.exit(0 if ok else 1)


if __name__ == "__main__":
    main()
